""" Config file for the project """

# Dataset
TRAINING_SET_IMAGE_COUNT = 60000
TESTING_SET_IMAGE_COUNT = 10000
IMAGE_WIDTH = 28

# GUI
GUI_ENABLED = False

# Neural Network Drawing
DRAW_NEURALNET_ENABLED = True
DRAW_NEURALNET_CONNECTIONS = True
DRAW_NEURALNET_CONNECTIONS_MAX_LIMIT = 300
DRAW_ANTIALIASING_MSAA = 2